services:
  - type: web
    name: n8n
    env: docker
    region: oregon
    plan: standard
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PGHOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: PGPORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: PGUSER
        fromDatabase:
          name: n8n-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: WEBHOOK_URL
        value: https://<CHANGEME>.com/

      # ⭐ ADD THESE TWO LINES
      - key: N8N_TRUST_PROXY
        value: "true"
      - key: N8N_ENABLE_X_FORWARDED_FOR
        value: "true"

    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n
      sizeGB: 2

databases:
  - name: n8n-db
    plan: basic-256mb
